### ISSUE TITLE
Bad class naming

### ISSUE THREAD

**Issue by HuyaneMatsu** [m0nk3ybraindead/thigh_api#1]
https://github.com/m0nk3ybraindead/thigh_api/blob/aabef6a465fdc063f4fc22e74c8d1d1980772a39/users/serializers.py#L8

Please just name it `AuthTokenSerializer`. So simple.

Thanks.

**Comment by m0nk3ybraindead** [comment]
Would naming it to `CustomAuthTokenSerializer` be fine?

**Comment by HuyaneMatsu** [comment]
no.

**Comment by m0nk3ybraindead** [comment]
I want to avoid naming conflicts

**Comment by m0nk3ybraindead** [comment]
I guess naming it `Custom...` is better

**Comment by HuyaneMatsu** [comment]
It is not Java, Jeez.

**Comment by m0nk3ybraindead** [comment]
It's bad design, if you want to import `AuthTokenSerializer` it would be hard to know what AuthTokenSerializer you are using.
